// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb.proto

package pb_gen

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type HttpProxyRequest struct {
	Uuid                 string            `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Method               string            `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	Url                  string            `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	Headers              map[string]string `protobuf:"bytes,4,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Body                 []byte            `protobuf:"bytes,5,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *HttpProxyRequest) Reset()         { *m = HttpProxyRequest{} }
func (m *HttpProxyRequest) String() string { return proto.CompactTextString(m) }
func (*HttpProxyRequest) ProtoMessage()    {}
func (*HttpProxyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{0}
}

func (m *HttpProxyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HttpProxyRequest.Unmarshal(m, b)
}
func (m *HttpProxyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HttpProxyRequest.Marshal(b, m, deterministic)
}
func (m *HttpProxyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HttpProxyRequest.Merge(m, src)
}
func (m *HttpProxyRequest) XXX_Size() int {
	return xxx_messageInfo_HttpProxyRequest.Size(m)
}
func (m *HttpProxyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HttpProxyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HttpProxyRequest proto.InternalMessageInfo

func (m *HttpProxyRequest) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *HttpProxyRequest) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *HttpProxyRequest) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *HttpProxyRequest) GetHeaders() map[string]string {
	if m != nil {
		return m.Headers
	}
	return nil
}

func (m *HttpProxyRequest) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

type HttpProxyResponse struct {
	Uuid                 string            `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Status               int32             `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	Headers              map[string]string `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Body                 []byte            `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *HttpProxyResponse) Reset()         { *m = HttpProxyResponse{} }
func (m *HttpProxyResponse) String() string { return proto.CompactTextString(m) }
func (*HttpProxyResponse) ProtoMessage()    {}
func (*HttpProxyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{1}
}

func (m *HttpProxyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HttpProxyResponse.Unmarshal(m, b)
}
func (m *HttpProxyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HttpProxyResponse.Marshal(b, m, deterministic)
}
func (m *HttpProxyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HttpProxyResponse.Merge(m, src)
}
func (m *HttpProxyResponse) XXX_Size() int {
	return xxx_messageInfo_HttpProxyResponse.Size(m)
}
func (m *HttpProxyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HttpProxyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HttpProxyResponse proto.InternalMessageInfo

func (m *HttpProxyResponse) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *HttpProxyResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *HttpProxyResponse) GetHeaders() map[string]string {
	if m != nil {
		return m.Headers
	}
	return nil
}

func (m *HttpProxyResponse) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

func init() {
	proto.RegisterType((*HttpProxyRequest)(nil), "pb_gen.HttpProxyRequest")
	proto.RegisterMapType((map[string]string)(nil), "pb_gen.HttpProxyRequest.HeadersEntry")
	proto.RegisterType((*HttpProxyResponse)(nil), "pb_gen.HttpProxyResponse")
	proto.RegisterMapType((map[string]string)(nil), "pb_gen.HttpProxyResponse.HeadersEntry")
}

func init() { proto.RegisterFile("pb.proto", fileDescriptor_f80abaa17e25ccc8) }

var fileDescriptor_f80abaa17e25ccc8 = []byte{
	// 282 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x92, 0xcd, 0x4a, 0xfb, 0x40,
	0x14, 0xc5, 0x99, 0xe6, 0xe3, 0xff, 0xef, 0xb5, 0x42, 0xbd, 0x88, 0x8c, 0x5d, 0x85, 0x82, 0x92,
	0x55, 0x90, 0xba, 0x91, 0x6e, 0x74, 0xa1, 0xd0, 0x65, 0x89, 0xb8, 0x96, 0xa4, 0xb9, 0xd8, 0x60,
	0xcd, 0x8c, 0xf3, 0x51, 0xcc, 0x63, 0xfa, 0x08, 0xbe, 0x89, 0x64, 0x12, 0xb5, 0x88, 0xc1, 0x8d,
	0xbb, 0x73, 0x2e, 0x37, 0xf7, 0x9c, 0x1f, 0x19, 0xf8, 0x2f, 0xf3, 0x44, 0x2a, 0x61, 0x04, 0x86,
	0x32, 0xbf, 0x7f, 0xa0, 0x6a, 0xfa, 0xc6, 0x60, 0xbc, 0x30, 0x46, 0x2e, 0x95, 0x78, 0xa9, 0x53,
	0x7a, 0xb6, 0xa4, 0x0d, 0x22, 0xf8, 0xd6, 0x96, 0x05, 0x67, 0x11, 0x8b, 0x87, 0xa9, 0xd3, 0x78,
	0x04, 0xe1, 0x13, 0x99, 0xb5, 0x28, 0xf8, 0xc0, 0x4d, 0x3b, 0x87, 0x63, 0xf0, 0xac, 0xda, 0x70,
	0xcf, 0x0d, 0x1b, 0x89, 0x97, 0xf0, 0x6f, 0x4d, 0x59, 0x41, 0x4a, 0x73, 0x3f, 0xf2, 0xe2, 0xbd,
	0xd9, 0x49, 0xd2, 0x86, 0x25, 0xdf, 0x83, 0x92, 0x45, 0xbb, 0x77, 0x53, 0x19, 0x55, 0xa7, 0x1f,
	0x5f, 0x35, 0xf1, 0xb9, 0x28, 0x6a, 0x1e, 0x44, 0x2c, 0x1e, 0xa5, 0x4e, 0x4f, 0xe6, 0x30, 0xda,
	0x5d, 0x6e, 0x62, 0x1f, 0xa9, 0xee, 0x1a, 0x36, 0x12, 0x0f, 0x21, 0xd8, 0x66, 0x1b, 0x4b, 0x5d,
	0xbf, 0xd6, 0xcc, 0x07, 0x17, 0x6c, 0xfa, 0xca, 0xe0, 0x60, 0x27, 0x5a, 0x4b, 0x51, 0x69, 0xea,
	0x83, 0xd4, 0x26, 0x33, 0x56, 0xbb, 0x23, 0x41, 0xda, 0x39, 0xbc, 0xfa, 0x42, 0xf2, 0x1c, 0xd2,
	0xe9, 0x0f, 0x48, 0xed, 0xdd, 0x5f, 0x98, 0xfc, 0xbf, 0x61, 0x9a, 0xdd, 0xc1, 0xfe, 0x52, 0x95,
	0xd5, 0x8a, 0x6e, 0x49, 0x6d, 0xcb, 0x15, 0xe1, 0x35, 0x0c, 0x3f, 0xbb, 0xe0, 0x71, 0x6f, 0xbd,
	0x09, 0xef, 0xfb, 0x19, 0x31, 0x3b, 0x63, 0x79, 0xe8, 0x5e, 0xc7, 0xf9, 0x7b, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x5e, 0x43, 0x0a, 0x5f, 0x29, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// PrinceServiceClient is the client API for PrinceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PrinceServiceClient interface {
	HttpProxy(ctx context.Context, opts ...grpc.CallOption) (PrinceService_HttpProxyClient, error)
}

type princeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPrinceServiceClient(cc grpc.ClientConnInterface) PrinceServiceClient {
	return &princeServiceClient{cc}
}

func (c *princeServiceClient) HttpProxy(ctx context.Context, opts ...grpc.CallOption) (PrinceService_HttpProxyClient, error) {
	stream, err := c.cc.NewStream(ctx, &_PrinceService_serviceDesc.Streams[0], "/pb_gen.PrinceService/HttpProxy", opts...)
	if err != nil {
		return nil, err
	}
	x := &princeServiceHttpProxyClient{stream}
	return x, nil
}

type PrinceService_HttpProxyClient interface {
	Send(*HttpProxyResponse) error
	Recv() (*HttpProxyRequest, error)
	grpc.ClientStream
}

type princeServiceHttpProxyClient struct {
	grpc.ClientStream
}

func (x *princeServiceHttpProxyClient) Send(m *HttpProxyResponse) error {
	return x.ClientStream.SendMsg(m)
}

func (x *princeServiceHttpProxyClient) Recv() (*HttpProxyRequest, error) {
	m := new(HttpProxyRequest)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// PrinceServiceServer is the server API for PrinceService service.
type PrinceServiceServer interface {
	HttpProxy(PrinceService_HttpProxyServer) error
}

// UnimplementedPrinceServiceServer can be embedded to have forward compatible implementations.
type UnimplementedPrinceServiceServer struct {
}

func (*UnimplementedPrinceServiceServer) HttpProxy(srv PrinceService_HttpProxyServer) error {
	return status.Errorf(codes.Unimplemented, "method HttpProxy not implemented")
}

func RegisterPrinceServiceServer(s *grpc.Server, srv PrinceServiceServer) {
	s.RegisterService(&_PrinceService_serviceDesc, srv)
}

func _PrinceService_HttpProxy_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PrinceServiceServer).HttpProxy(&princeServiceHttpProxyServer{stream})
}

type PrinceService_HttpProxyServer interface {
	Send(*HttpProxyRequest) error
	Recv() (*HttpProxyResponse, error)
	grpc.ServerStream
}

type princeServiceHttpProxyServer struct {
	grpc.ServerStream
}

func (x *princeServiceHttpProxyServer) Send(m *HttpProxyRequest) error {
	return x.ServerStream.SendMsg(m)
}

func (x *princeServiceHttpProxyServer) Recv() (*HttpProxyResponse, error) {
	m := new(HttpProxyResponse)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _PrinceService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb_gen.PrinceService",
	HandlerType: (*PrinceServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "HttpProxy",
			Handler:       _PrinceService_HttpProxy_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "pb.proto",
}
